<?php
/* application */
  /*
   *  Application model/data logic is split between
   *  1) attachments      (model/attach.php)
   *  2) application fields (model/application.php)
   *
   *  Template Input
   *  ==============
   *  This template accepts input for its contents from the following variables:
   *
   *  $app - The application field data
   *  (e.g., used to load previously submitted data into the edit form for re-editing)
   *
   *  This contains an application in the application object format described in model/application.php.
   *  E.g., $app["firstname"] has the "firstname" field, $app[0]["to"] would represent the first job's "to"
   *  field (if present).
   *
   *  $error - errors from last failed submission attempt
   *  (e.g., user submits an application with an attachment that didn't transfer properly)
   *
   *  $error["login"]
   *      This contains a login error message, if any.
   *  $error["app"]
   *      This contains error messages specific to particular application fields.
   *      These can be generated by validation errors, for example.
   *      The structure corresponds to the $app object.  For example, $error["app"]["firstname"] would
   *      contain an error message about the "firstname" field that had been submitted
   *
   *  If a message is the value TRUE, then it merely indicates an error without a specific message.
   *  Otherwise, it should be a string or other echo'able value describing the error.
   *
   *  Form Output
   *  ===========
   *  The form also submits data back to the server.  This 'output' format does not quite match
   *  the input formats (sometimes because I didn't plan and sometimes because I did) but is similar.
   *
   *  The model/application.php:app_parse() parses submitted form data into an application object,
   *  so it should be consulted to see the names that form fields should be given for application data.
   *  For attachments, model/attach.php should be consulted.
   *
   *  See model/attach.php for details about attachments.
   *
   */

    $title = "Editing Application";
    $page_css = "css/application.css";
    $page_head = "<script type='text/javascript' src='js/validator_full.js'></script>\n" .
            "<script type='text/javascript' src='js/req.js'></script>\n" .
            "<script type='text/javascript' src='js/app.js'></script>";


  // selected checkbox / radio button
  $SELECT = 'checked="checked"';
  $SEL2 = 'selected';


  // HTML escape values
  app_htmlescape($app);
  $jobs = $app["jobs"];
  $app = $app["details"];

   //Some experiments for PHP-based validation
   //$error = array("page" => array("firstname"));
   //$pgerr = array("att_desc_0" => 1, "prev0_salary" => 1);

   /* Map $app["reftype"] and $app["refdetail"] into a hashtable based on the
    actual contents of the webpage.
  */
   $hears = array(
    "newspaper" => false,
    "craigslist" => false,
    "radio" => false,
    "commission" => false,
    "wordOfMouth" => false,
    "online" => false,
    "other" =>false
   );
   $heard = array(
    "newspaper" => "",
    "radio" => "",
    "online" => "",
    "other" => ""
   );

   $data = &$app;
   $hs = isset($data["reftype"]) ? $data["reftype"] : "";//other";
   if(!isset($hears[$hs])) $hs = ""; // unknown type
   switch($hs) {
    case "online":
    case "radio":
    case "newspaper":
    case "other":
      $heard[$hs] = isset($data["refdetail"]) ? $data["refdetail"] : "";
      // fall-through
    case "craigslist":
    case "commission":
    case "wordOfMouth":
      $hears[$hs] = true;
      break;
    default:
      // should not be able to get here
      //logfail(__FILE__ + ":" + __LINE__ + " assertion failed: hearsrc default in switch");
      break;
   }

   include("pagewrap.inc.php");
?>



<!-- O HTML reader, no one is using this, but maybe we'll bring it back later. ;-)

<form method="get" action="index.php/">
<div style="border: 2px solid red; margin-left: 60px; margin-right: 60px;margin-bottom: 20px;">
<table>
<tr>
<td style="border:0;font-size: 80%;" colspan=3>
If you had saved but not submitted an application on the previous version
of the application portal, you can login here to continue your application
using your original username/email and password.  Also, in some cases,
the hiring coordinator may provide you with a login to allow you to modify
and resubmit a previously submitted application.
<tr>
<td style="border:0;font-size: 80%;" >Username/Email: <input name="uid" type="text">
<td style="border:0;font-size: 80%;" >Password: <input name="pw" type="password">
<td style="border:0;font-size: 80%;" colspan=1>
<input type="hidden" name="action" value="edit">
<input type="hidden" name="token" value="<?php echo (isset($token) ? $token : ""); ?>">
<button type="submit">Login</button>
</table>
</div>
-->
<?php
$act_error = isset($error["login"]) ? $error["login"] : 0;
if(isset($act_error) and $act_error != 0) {
   echo "<p>Authentication failed: ";
   if($act_error == AUTH_BADUID)
    echo "bad username";
   elseif($act_error == AUTH_BADPW)
    echo "bad password";
   else
    echo "unknown";
   echo "</p>";
}
?>
<!--</form>-->







<form style="margin-top: 50px" enctype="multipart/form-data"  method="post" action="index.php">

<h1 style="font-size: 140%;margin-bottom:0;">Application</h1>

<table class="app" border=1 cellspacing=5 cellpadding=5 style="table-layout:fixed">
<tr>
<td colspan=12>
NFS is an Equal Opportunity Employer.  Our hiring decisions are made without regard to race, color, religion, political affiliation, national origin, disability, marital status, gender, or age.
<tr >
<td colspan=12>
<span class="heading">Personal Information</span>
<tr>
<td <?php echo (isset($pgerr["firstname"])?"class='error'":""); ?> id="firstname" colspan=6 >
First Name: <input name="firstname" style="width:75%" value="<?php echo $app["firstname"] ?>">
</td>
<td <?php echo (isset($pgerr["lastname"])?"class='error'":"");?> id="lastname" colspan=6 >
Last Name: <input name="lastname" style="width:75%" value="<?php echo $app["lastname"] ?>">
</td>
</tr>
<tr>
<td <?php echo (isset($pgerr["nickname"])?"class='error'":"");?> id="nickname" colspan=12>
Preferred Name/Nickname: <input name="nickname" style="width:75%" value="<?php echo $app["nickname"] ?>">
</td>
</tr>
<tr>
<td <?php echo (isset($pgerr["street"])?"class='error'":"");?> id="street" colspan=3>
Street Address: <input style="width:90%;" name="street" value="<?php echo $app["street"] ?>">
<td <?php echo (isset($pgerr["city"])?"class='error'":"");?> id="city" colspan=3>
City: <input style="width:90%;" name="city" value="<?php echo $app["city"] ?>">
<td <?php echo (isset($pgerr["state"])?"class='error'":"");?> id="state" colspan=3>
State:
<select name="state" >
       <option value=""></option>
       <?php foreach($sug["State"] as $item) {
        $detail = $item["detail"];
        $selected = $app["state"] === $detail ? $SEL2 : "";
        $detail = htmlentities($detail);
        echo "<option $selected value='$detail'>$detail</option>";
      } ?>
</select>
<td <?php echo (isset($pgerr["zip"])?"class='error'":"");?> id="zip" colspan=3>
Zip Code: <input style="width:90%;" name="zip" value="<?php echo $app["zip"] ?>">
</tr>
<tr>
<td <?php echo (isset($pgerr["homeph"])?"class='error'":"");?> id="homeph" colspan=6 >
Home Phone No.: <input name="homeph" style="width:75%" value="<?php echo $app["homeph"] ?>">
<td <?php echo (isset($pgerr["cellph"])?"class='error'":"");?> id="cellph" colspan=6 >
Cell Phone No.: <input name="cellph" style="width:75%" value="<?php echo $app["cellph"] ?>">
</tr>
<tr>
<td <?php echo (isset($pgerr["email"])?"class='error'":"");?> id="email" colspan=6>
Email Address: <input name="email" style="width:75%" value="<?php echo $app["email"] ?>">
<td <?php echo (isset($pgerr["pref_contact_method"])?"class='error'":"");?> id="pref_contact_method" colspan=6>
Preferred Method of Contact: <input name="pref_contact_method" style="width:75%" value="<?php echo $app["pref_contact_method"] ?>">
</td>
</tr>


<tr>
<td colspan=12>
<span class="heading">Employment Desired</span>
<tr>
<td <?php echo (isset($pgerr["posname"])?"class='error'":"");?> id="posname" colspan=12>
Position Applying for?
<select name="posname">
<option value=""></option>
<option value="svctech" <?php echo ($app["posname"] == "svctech" ? $SEL2 : "") ?> >Service Technician</option>
<option value="office"  <?php echo ($app["posname"] == "office" ? $SEL2 : "") ?> >Office Staff</option>
<option value="other" <?php echo ($app["posname"] == "other" ? $SEL2 : "") ?> >Other</option>
</select>
<tr>
<td <?php echo (isset($pgerr["posdesc"])?"class='error'":"");?> id="posdesc" colspan=12>
If other, please describe.<br>
<textarea name="posdesc" rows=5 cols=5 style="height: 5em; width:100%"><?php echo $app["posdesc"]?></textarea>
<tr>
<td colspan=12>
How did you hear of this position?<br>
   <table id="hearsrc_source" <?php echo ((isset($pgerr["hearsrc_source"]) or isset($pgerr["hearsrc_detail"]))?"class='error'":"");?> cellspacing=10 cellpadding=3>
   <tr>
   <td style="border:none"><input name="reftype" type="radio" value="craigslist" <?php echo ($hears["craigslist"] ? $SELECT : "") ?> >
   <td><span style="font-weight:bold">Craigslist</span>
   <tr>
   <td style="border:none"><input name="reftype" type="radio" value="newspaper"  <?php echo ($hears["newspaper"] ? $SELECT : "") ?> >
   <td><span style="font-weight:bold">Newspaper</span><br>Which newspaper?
       <select id="hearsrc_newspaper" name="refdetail_newspaper" >
       <option value=""></option>
       <?php foreach($sug["Newspaper"] as $item) {
        $detail = $item["detail"];
        $selected = $heard["newspaper"] === $detail ? $SEL2 : "";
        $detail = htmlentities($detail);
        echo "<option $selected value='$detail'>$detail</option>";
      } ?>
       </select>
   <tr>
   <td style="border:none"><input name="reftype" type="radio" value="radio" <?php echo ($hears["radio"] ? $SELECT : "") ?> >
   <td><span style="font-weight:bold">Radio</span><br>Which station?
       <select id="hearsrc_radio" name="refdetail_radio">
       <option value=""></option>
         <?php foreach($sug["Radio"] as $item) {
        $detail = $item["detail"];
        $selected = $heard["radio"] === $detail ? $SEL2 : "";
        $detail = htmlentities($detail);
        echo "<option $selected value='$detail'>$detail</option>";
      } ?>
       </select>
   <tr>
   <td style="border:none"><input name="reftype" type="radio" value="commission" <?php echo ($hears["commission"] ? $SELECT : "") ?> >
   <td><span style="font-weight:bold">Employment Commission</span>
   <tr>
   <td style="border:none"><input name="reftype" type="radio" value="wordOfMouth" <?php echo ($hears["wordOfMouth"] ? $SELECT : "") ?> >
   <td><span style="font-weight:bold">Word of Mouth</span>
   <tr>
   <td style="border:none"><input name="reftype" type="radio" value="online" <?php echo ($hears["online"] ? $SELECT : "") ?> >
   <td><span style="font-weight:bold">Online</span><br>What is the web address?<br>
       <select id="hearsrc_online" name="refdetail_online">
       <option value=""></option>
         <?php foreach($sug["Online"] as $item) {
        $detail = $item["detail"];
        $selected = $heard["online"] === $detail ? $SEL2 : "";
        $detail = htmlentities($detail);
        echo "<option $selected value='$detail'>$detail</option>";
      } ?>
       </select>
   <tr>
   <td style="border:none"><input name="reftype" type="radio" value="other" <?php echo ($hears["other"] ? $SELECT : "") ?> >
   <td><span style="font-weight:bold">Other</span><br>How?  <input id="hearsrc_other" name="refdetail_other" type="text" value="<?php echo $heard["other"] ?>">
   </table>

<tr>
<td <?php echo (isset($pgerr["salary"])?"class='error'":"");?> id="salary" colspan=6>
Salary desired? <input name="salary" style="width:50%" value="<?php echo $app["salary"] ?>">
<tr>
<td <?php echo (isset($pgerr["prevapplied"])?"class='error'":"");?> id="prevapplied" colspan=6>
Have you applied with NFS previously?<br>
(<input name="prevapplied" type="radio" value="1" <?php echo ($app["prevapplied"]==="1"?$SELECT:"") ?> >Yes)
(<input name="prevapplied" type="radio" value="0" <?php echo ($app["prevapplied"]==="0"?$SELECT:"") ?> >No)

<td <?php echo (isset($pgerr["whenapplied"])?"class='error'":"");?> id="whenapplied" colspan=6>
If so, when?
<input name="whenapplied" type="text" value="<?php echo $app["whenapplied"] ?>">
<tr>
<td <?php echo (isset($pgerr["grade"])?"class='error'":"");?> id="grade" colspan=12>
Select highest grade completed:
<input type="radio" name="grade" value="9" <?php echo ($app["grade"] == "9" ? $SELECT : "") ?> >9
<input type="radio" name="grade" value="10" <?php echo ($app["grade"] == "10" ? $SELECT : "") ?> >10
<input type="radio" name="grade" value="11" <?php echo ($app["grade"] == "11" ? $SELECT : "") ?> >11
<input type="radio" name="grade" value="12" <?php echo ($app["grade"] == "12" ? $SELECT : "") ?> >12
<input type="radio" name="grade" value="equiv" <?php echo ($app["grade"] == "equiv" ? $SELECT : "") ?> >HS equivalency

<tr>
<td colspan=12>
<span class="heading">Name of School(s)</span>
<tr>
<td <?php echo (isset($pgerr["highschool"])?"class='error'":"");?> id="highschool" colspan=6>
<div>High School</div>
<input name="highschool" style="clear:left; width:75%" value="<?php echo $app["highschool"] ?>">
<td <?php echo (isset($pgerr["hsgrad"])?"class='error'":"");?> id="hsgrad" colspan=6>
Graduated?
(<input name="hsgrad" type="radio" value="1" <?php echo ($app["hsgrad"]==="1"?$SELECT:"") ?> >Yes)
(<input name="hsgrad" type="radio" value="0" <?php echo ($app["hsgrad"]==="0"?$SELECT:"") ?> >No)
<tr>
<td <?php echo (isset($pgerr["college"])?"class='error'":"");?> id="college" colspan=6>
College or Trade School
<input type="text" name="college" style="width:75%" value="<?php echo $app["college"] ?>">
<td <?php echo (isset($pgerr["colgrad"])?"class='error'":"");?> id="colgrad" colspan=6>
Degree Earned?
(<input name="colgrad" type="radio" value="1" <?php echo ($app["colgrad"]==="1"?$SELECT:"") ?> >Yes)
(<input name="colgrad" type="radio" value="0" <?php echo ($app["colgrad"]==="0"?$SELECT:"") ?> >No)


<tr>
<td colspan=12>
<span class="heading">Military Background</span>
<tr>
<td <?php echo (isset($pgerr["military"])?"class='error'":"");?> id="military" colspan=6>
Unit and Ranking
<input name="military" type="text" style="width:75%" value="<?php echo $app["military"] ?>">

<tr>
<td colspan=12>
<span class="heading">Licensures</span>
<tr>
<td colspan=12 style="border:red dashed; font-weight: bold;">
A 3 Year Driving Record from the DMV must be submitted separately and in addition to
this form to complete your application.  You may fax a copy to the Hiring Coordinator at
(434) 842-9349 or send a copy by email to
<a href="mailto:careers@nationalfilterservice.com">careers@nationalfilterservice.com</a>
<tr>
<td <?php echo (isset($pgerr["licensetype"])?"class='error'":"");?> id="licensetype" colspan=5>
Type of license (including driver's license)
<input name="licensetype" type="text" style="width:75%" value="<?php echo $app["licensetype"] ?>">
<td <?php echo (isset($pgerr["licenseno"])?"class='error'":"");?> id="licenseno" colspan=4>
License No.
<input name="licenseno" type="text" style="width:75%" value="<?php echo $app["licenseno"] ?>">
<td <?php echo (isset($pgerr["licensestate"])?"class='error'":"");?> id="licensestate" colspan=3>
Issuing State
<input name="licensestate" type="text" style="width:75%" value="<?php echo $app["licensestate"] ?>">

<tr>
<td colspan=12>
<span class="heading">Work Experience</span>
<tr>
<td <?php echo (isset($pgerr["employed"])?"class='error'":"");?> id="employed" colspan=12>
Are you currently employed?
(<input name="employed" type="radio" value="1" <?php echo ($app["employed"]==="1"?$SELECT:"") ?> >Yes)
(<input name="employed" type="radio" value="0" <?php echo ($app["employed"]==="0"?$SELECT:"") ?> >No)
<tr>
<td <?php echo (isset($pgerr["neednotice"])?"class='error'":"");?> id="neednotice" colspan=6>
If yes, do you need to provide your current employer notice?
(<input name="neednotice" type="radio" value="1" <?php echo ($app["neednotice"]==="1"?$SELECT:"") ?> >Yes)
(<input name="neednotice" type="radio" value="0" <?php echo ($app["neednotice"]==="0"?$SELECT:"") ?> >No)
<td <?php echo (isset($pgerr["notice"])?"class='error'":"");?> id="notice" colspan=6>
How many weeks?
<input type="radio" name="notice" value="1" <?php echo ($app["notice"] == "1" ? $SELECT : "") ?> >One
<input type="radio" name="notice" value="2" <?php echo ($app["notice"] == "2" ? $SELECT : "") ?> >Two
<tr>
<td colspan=12>
<label for="can_contact_emp">May we contact your employer?</label>
<input type="radio" name="can_contact_emp" id="can_contact_emp" value="1" <?php echo ($app["can_contact_emp"]==="1"?$SELECT:"") ?> />Yes
<input type="radio" name="can_contact_emp" id="can_contact_emp" value="0" <?php echo ($app["can_contact_emp"]==="1"?$SELECT:"") ?> />No
</td>
</tr>
<tr>
<td colspan=12>
<span class="emph">Please list your most recent employment first.</span><br/>
</td>
</tr>
<tr>
<td colspan=2>
Dates
<td colspan=2>
Company Name / <br/>Address/Phone number
<td colspan=2>
Supervisor Name
<td colspan=2>
Job Title/Responsibilities&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<td colspan=2>
Reason for Leaving
<td colspan=2>
Salary
<?php
   for($i=0; isset($jobs[$i]); $i++) {
    $j = $jobs[$i];
?>
  <tr id="job<?php echo $i?>" >
  <td colspan=2>
  <div <?php echo (isset($pgerr["prev".$i."_to"])?"class='error'":"");?> id="to<?php echo $i?>">
  End:<br>
  <input name="prev<?php echo $i?>_to" type="text" style="width:70%" value="<?php echo $j["to"] ?>"><br>
  </div>
  <div <?php echo (isset($pgerr["prev".$i."_from"])?"class='error'":"");?> id="from<?php echo $i?>">
  Start:<br>
  <input name="prev<?php echo $i?>_from" type="text" style="width:70%" value="<?php echo $j["from"] ?>">
  </div>
  <td <?php echo (isset($pgerr["prev".$i."_company"])?"class='error'":"");?> id="company<?php echo $i?>" colspan=2>
  <div style="position:relative">
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_company" style="width:90%;"><?php echo $j["company"] ?></textarea>
  </div>
  <td <?php echo (isset($pgerr["prev".$i."_title"])?"class='error'":"");?> id="title<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_title" style="width:90%;"><?php echo $j["title"] ?></textarea>
  <td <?php echo (isset($pgerr["prev".$i."_duties"])?"class='error'":"");?> id="duties<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_duties" style="width:90%;"><?php echo $j["duties"] ?></textarea>
  <td <?php echo (isset($pgerr["prev".$i."_reason"])?"class='error'":"");?> id="reason<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_reason" style="width:90%;"><?php echo $j["reason"] ?></textarea>
  <td <?php echo (isset($pgerr["prev".$i."_salary"])?"class='error'":"");?> id="salary<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_salary" style="width:90%;"><?php echo $j["salary"] ?></textarea>
<?php
   }
   $jobcount = $i;
   for(; $i<=9; $i++) {
?>
  <tr <?php echo (isset($pgerr["job<?php echo $i?>"])?"class='error'":"");?> id="job<?php echo $i?>" style="display: none;">
  <td colspan=2>
  <div <?php echo (isset($pgerr["to<?php echo $i?>"])?"class='error'":"");?> id="to<?php echo $i?>">
  To:<br>
  <input name="prev<?php echo $i?>_to" type="text" style="width:70%" value=""><br>
  </div>
  <div <?php echo (isset($pgerr["from<?php echo $i?>"])?"class='error'":"");?> id="from<?php echo $i?>">
  From:<br>
  <input name="prev<?php echo $i?>_from" type="text" style="width:70%" value="">
  </div>
  <td <?php echo (isset($pgerr["company<?php echo $i?>"])?"class='error'":"");?> id="company<?php echo $i?>" colspan=2>
  <div style="position:relative">
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_company" style="width:90%;"></textarea>
  </div>
  <td <?php echo (isset($pgerr["title<?php echo $i?>"])?"class='error'":"");?> id="title<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_title" style="width:90%;"></textarea>
  <td <?php echo (isset($pgerr["duties<?php echo $i?>"])?"class='error'":"");?> id="duties<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_duties" style="width:90%;"></textarea>
  <td <?php echo (isset($pgerr["reason<?php echo $i?>"])?"class='error'":"");?> id="reason<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_reason" style="width:90%;"></textarea>
  <td <?php echo (isset($pgerr["salary<?php echo $i?>"])?"class='error'":"");?> id="salary<?php echo $i?>" colspan=2>
  <textarea cols=2 rows=5 name="prev<?php echo $i?>_salary" style="width:90%;"></textarea>
<?php
   }
?>
<tr>
<td colspan=12>
<?php
   if($jobcount == 0) {
    echo "<span style='font-weight: bold'>You don't have any previous jobs listed on your application!</span><br>";
   }
?>
<a href="javascript:plusjob()">Click here</a> if you wish to list more jobs (up to a maximum of ten).
<tr>
<td colspan=12>
<span class="heading">References</span>
<tr>
<td colspan=12>
Provide <span class="emph">business</span> references, beginning with your last supervisor's name or co-worker's name.
<tr>
<td colspan=4>
Company Name
<td colspan=4>
Contact Person / Title
<td colspan=4>
Area code and phone no./ext.
  <tr>
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref1_name"])?"class='error'":"");?> id="ref1_name" name="ref1_name" type="text" style="width:90%; " value="<?php echo $app["ref1_name"] ?>">
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref1_title"])?"class='error'":"");?> id="ref1_title" name="ref1_title" type="text" style="width:90%; " value="<?php echo $app["ref1_title"] ?>">
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref1_phone"])?"class='error'":"");?> id="ref1_phone" name="ref1_phone" type="text" style="width:90%; " value="<?php echo $app["ref1_phone"] ?>">
  <tr>
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref2_name"])?"class='error'":"");?> id="ref2_name" name="ref2_name" type="text" style="width:90%; " value="<?php echo $app["ref2_name"] ?>">
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref2_title"])?"class='error'":"");?> id="ref2_title" name="ref2_title" type="text" style="width:90%; " value="<?php echo $app["ref2_title"] ?>">
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref2_phone"])?"class='error'":"");?> id="ref2_phone" name="ref2_phone" type="text" style="width:90%; " value="<?php echo $app["ref2_phone"] ?>">
  <tr>
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref3_name"])?"class='error'":"");?> id="ref3_name" name="ref3_name" type="text" style="width:90%; " value="<?php echo $app["ref3_name"] ?>">
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref3_title"])?"class='error'":"");?> id="ref3_title" name="ref3_title" type="text" style="width:90%; " value="<?php echo $app["ref3_title"] ?>">
  <td colspan=4>
  <input <?php echo (isset($pgerr["ref3_phone"])?"class='error'":"");?> id="ref3_phone" name="ref3_phone" type="text" style="width:90%; " value="<?php echo $app["ref3_phone"] ?>">

<tr>
<td <?php echo (isset($pgerr["canemploy"])?"class='error'":"");?> id="canemploy" colspan=12>
For the purpose of compliance with the Immigration Reform and Control Act, are you legally eligible for employment in the United States?
(<input name="canemploy" type="radio" value="1" <?php echo (empty($app["canemploy"]) || $app["canemploy"]==="1"?$SELECT:"") ?> >Yes)
(<input name="canemploy" type="radio" value="0" <?php echo ($app["canemploy"]==="0"?$SELECT:"") ?> >No)
<tr>
<td colspan=12>
<span class="small">
Under the Immigration Reform and Control Act of 1986, you will be required to fill out a certification
verifying that you are eligible to be employed and verify your identity.  Furthere, you will be required
to provide documentation to that effect should you be employed with NFS.
</span>
</td>


<tr>
<td colspan=12>
<span class="heading">Authorization</span>
<tr>
<td colspan=12>
&quot;I hereby certify that all entries on both sides and attachments are true and complete, and I agree and understand that any falsification of information herein, regardless of time of discovery,
may cause forfeiture on my part of any employment with National Filter Service. I understand that all information on this application is subject to verification and I consent to criminal history
background checks. I also consent that you may contact references, former employers and education institutions listed regarding this application. I further authorize that National Filter Service
to rely upon and use, as it sees fit, any information received from such contacts. Information contained on this application may be disseminated to other agencies, on a need-to-know basis for
good cause shown as determined by National Filter Service.&quot;
<tr>
<td <?php echo (isset($pgerr["auth_date"])?"class='error'":"");?> id="auth_date" colspan=4>
Date<br>
<input name="auth_date" type="text" style="width: 75%" value="<?php echo $app["auth_date"] ?>">
<td <?php echo (isset($pgerr["auth_sig"])?"class='error'":"");?> id="auth_sig" colspan=8>
Application Signature<br>
<input name="auth_sig" type="text" style="width: 75%" value="<?php echo $app["auth_sig"] ?>">

<tr>
<td colspan=12>
<p>
I certify and declare under penalty of perjury under relevant state and federal law that the information contained in my employment application is complete, true, and accurate. I acknowledge that
falsification or omission of information may result in immediate dismissal or retraction of any offer of employment.
</p>
<p>
In consideration of National Filter Service, Inc. (herein referred to as <strong>EMPLOYER</strong>) review of my application for employment, I hereby voluntarily consent to and authorize <strong>EMPLOYER</strong>, or its authorized
agents bearing this release or copy thereof, to obtain a consumer report for employment purposes. I agree that this consumer report may include any of the following:
</p>
<ul>
<li>Employment Verification, Education Verification, Credentials Verification</li>
<li>Personal Identity Verifications, Past Employment Verification, Reference Checks</li>
<li>Criminal Records, Civil Cases, Motor Vehicle Records</li>
</ul>
<p>
I authorize all persons and organizations that may have information relevant to this research to disclose such information to <strong>EMPLOYER</strong> or its authorized agents. I hereby release <strong>EMPLOYER</strong>, its
authorized agents, and all persons and organizations providing information from all claims and liabilities of any nature in connection with this research. I hereby further authorize that a
photocopy of this authorization may be considered as valid as the original.
</p>

<pre <?php echo (isset($pgerr["elec_name"])?"class='error'":"");?> id="elec_name">Printed Name:         <input name="elec_name" type="text" style="width:50%; margin: auto 5%;" value="<?php echo $app["elec_name"] ?>"></pre>
<pre <?php echo (isset($pgerr["elec_birth"])?"class='error'":"");?> id="elec_birth">Date of Birth:        <input name="elec_birth" type="text" style="width:50%; margin: auto 5%;"  value="<?php echo $app["elec_birth"] ?>"></pre>
<pre <?php echo (isset($pgerr["elec_ssn"])?"class='error'":"");?> id="elec_ssn">Social Security Number:  <input name="elec_ssn" type="text" style="width:50%; margin: auto 5%;" value="<?php echo $app["elec_ssn"] ?>"></pre>
<div style="margin-left:5em;margin-right:5em;font-size: small">Note: the social security number is not required to submit an application, but will be required if hired.</div>
<pre <?php echo (isset($pgerr["elec_license"])?"class='error'":"");?> id="elec_license">Driver License &amp; State:  <input name="elec_license" type="text" style="width:50%; margin: auto 5%;" value="<?php echo $app["elec_license"] ?>"></pre>
<pre <?php echo (isset($pgerr["elec_sig"])?"class='error'":"");?> id="elec_sig">Signature:            <input name="elec_sig" type="text" style="width:50%; margin: auto 5%;" value="<?php echo $app["elec_sig"] ?>"></pre>
<pre <?php echo (isset($pgerr["elec_date"])?"class='error'":"");?> id="elec_date">Date of Signature:    <input name="elec_date" type="text" style="width:50%; margin: auto 5%;" value="<?php echo $app["elec_date"] ?>"></pre>

<tr>
  <td colspan="12">
    <span class="heading">Disclosure Regarding Consumer And/or Investigative Report</span>
  </td>
</tr>

<tr>
  <td colspan="12">
    <p>
    National Filter Service ("Company") may obtain information about you for employment purposes from a third party consumer reporting agency. Thus, you may be the subject of a "consumer report" and/or an "investigative consumer report" which may include information about your character, general reputation, personal characteristics, and/or mode of living, and which can involve personal interviews with sources such as your neighbors, friends, supervisors, or associates. These reports may contain information regarding your credit history, criminal history, social security verification, motor vehicle records ("driving records"), verification of your education or employment history, or other background checks. Further, you understand that information may be requested from various Federal, State, County and other agencies that maintain records concerning your past activities relating to your driving, criminal, civil, education, credit, and other experiences. Credit history will only be requested where such information is substantially related to the duties and responsibilities of the position for which you are applying.
    </p>

    <p>
    You have the right, upon written request made within a reasonable period of time after receipt of this notice, to request whether a consumer report has been conducted about you, disclosure of the nature and scope of any investigative consumer report, and to request a copy of your report. Please be advised that the nature and scope of the most common form of investigative consumer report obtained with regard to applicants for employment is an investigation into your employment and/or education history. The scope of this notice and authorization is all-encompassing, however, allowing the Company to obtain consumer reports and investigative consumer reports now and throughout the course of your employment to the extent permitted by law, unless you otherwise revoke your consent by providing written notification to Company. As a result, you should carefully consider whether to exercise your right to request disclosure of the nature and scope of any investigative consumer report. 
    </p>

    <p>
    The consumer and/or investigative consumer report(s) will be obtained from: 
    <strong>Accurate Background, Inc., 7515 Irvine Center Drive, Irvine, CA 92618, (800) 216-8024. 
    Accurate Background’s information and privacy policy can be found at <a href="www.accuratebackground.com" target="_blank">www.accuratebackground.com</a>.</strong>
    </p>

    <p>
    <strong>California applicants or employees only:</strong> Please check the appropriate box if you would like to receive a copy of your investigative consumer report or consumer credit report at no charge.
    </p>

    <p>
    <strong>Minnesota and Oklahoma applicants or employees only</strong>: Please check the appropriate box if you would like to receive a copy of your consumer report free of charge
    </p>

    <p>
    <strong>New York applicants or employees only:</strong> You have the right to inspect and receive a copy of any investigative consumer report requested by National Filter Service by contacting the consumer reporting agency identified above directly. You may also contact the Company to request the name, address and telephone number of the nearest unit of the consumer reporting agency designated to handle inquiries, which the Company shall provide within 5 days. Upon request, you will be informed whether or not a consumer report was requested by National Filter Service, and if such report was requested, informed of the name and address of the consumer reporting agency that furnished the report.
    </p>

    <p>
    <strong>Oregon applicants or employees only:</strong> Information describing your rights under federal and Oregon law regarding consumer identity theft protection, the storage and disposal of your credit information, and remedies available should you suspect or find that the Company has not maintained secured records is available to you upon request.
    </p>

    <p>
    <strong>Washington State applicants or employees only:</strong> You also have the right to request from the consumer reporting agency a written summary of your rights and remedies under the Washington Fair Credit Reporting Act
    </p>

    <p>
    For California, Oklahoma, or Minnesota employees and applicants: Please check the appropriate box to indicate if you would like to receive a copy of your consumer report free of charge.
    </p>

    <p>
    <label for="consumer-report-receive-copy-yes"><input id="consumer-report-receive-copy-yes" name="cons_receive_copy" type="radio" value="1"> Yes</label><br/>
    <label for="consumer-report-receive-copy-no"><input id="consumer-report-receive-copy-no" name="cons_receive_copy" type="radio" value="0" checked> No</label>
    </p>

    <p>
    <label for="cons_sig">Signature: <input type="text" id="cons_sig" name="cons_sig" /></label>
    <label for="cons_date">Date: <input type="text" id="cons_date" name="cons_date" /></label>
    </p>
  </td>
</tr>

<tr>
  <td colspan="12">
    <span class="heading">Acknowledgment And Authorization For Background Check</span>
  </td>
</tr>

<tr>
  <td colspan="12">
    <p>
    I acknowledge receipt of the DISCLOSURE REGARDING CONSUMER AND/OR INVESTIGATIVE REPORT and A SUMMARY OF YOUR RIGHTS UNDER THE FAIR CREDIT REPORTING ACT and certify that I have read and understand both of those documents. I hereby authorize the obtaining of "consumer reports" and/or "investigative consumer reports" by National Filter Service at any time after receipt of this authorization and throughout my employment, if applicable. To this end, I hereby authorize, without reservation, any law enforcement agency, administrator, local, state or federal agency, institution, school or university (public or private), information service bureau, employer, or insurance company to furnish any and all background information requested by <strong>Accurate Background, Inc., 7515 Irvine Center Drive, Irvine, CA 92618, (800) 216-8024,</strong> another outside organization acting on behalf of the Company, and/or the Company itself. 
    </p>

    <p>
    I understand that by signing my name below, that I am signing the Authorization form directing the background check as described above, and I certify that: 
    </p>

    <p <?php echo (isset($pgerr["have-read-disclosure"])?"class='error'":"") ?>>
    <label id="disc_have_read" for="disc_have_read_checkbox"><input type="checkbox" id="disc_have_read_checkbox" name="disc_have_read" value="1" /> I have received the Disclosure Regarding Consumer and/or Investigative Report, have read and received the Summary of Your Rights, and if a California resident/applicant, the A Summary of Your Rights Under the Provisions of California Civil Code §1786.22.</label>
    </p>

    <p <?php echo (isset($pgerr["signature-is-binding"])?"class='error'":"") ?>>
    <label id="disc_binding" for="disc_binding_checkbox"><input type="checkbox" id="disc_binding_checkbox" name="disc_binding" value="1" />  I understand that my signature now and throughout this process will be binding. Additionally, notices, documents, and communications may be provided electronically and will meet the requirements set forth under Federal and/or State law, as permitted by law. I agree that a facsimile ("fax"), electronic or printout of this authorization may be accepted with the same authority as the original.</label>
    </p>

    <p>
    <strong>California applicants or employees only:</strong> By signing below, you also acknowledge receipt of A SUMMARY OF YOUR RIGHTS UNDER THE PROVISIONS OF CALIFORNIA CIVIL CODE §1786.22.
    </p>

    <p>
    <strong>New York applicants or employees only:</strong> By signing below, you also acknowledge receipt of Article 23-A of the New York Correction Law.
    </p>

    <p <?php echo (isset($pgerr["disc_name"])?"class='error'":"") ?>>
    <label for="disc_name">Print Name: <input id="disc_name" name="disc_name" type="text" /></label>
    </p>

    <p <?php echo (isset($pgerr["disc_other_names"])?"class='error'":"") ?>>
    <label for="disc_other_names">Other Names Known By: <input id="disc_other_names" name="disc_other_names" /></label>
    </p>

    <p>
    <label for="disc_ssn">Social Security Number: <input id="disc_ssn" name="disc_ssn" type="text" /></label>
    </p>

    <p>
    <label for="disc_birth">Date of Birth: <input id="disc_birth" name="disc_birth" type="text" /></label>
    </p>

    <p>
    <label for="disc_license">Driver's License Number: <input id="disc_license" name="disc_license" type="text" /></label>
    </p>

    <p>
    <label for="disc_license_state">Driver's License State: <input id="disc_license_state" name="disc_license_state" type="text" /></label>
    </p>

    <p>
    <label for="disc_city">City: <input id="disc_city" name="disc_city" type="text" /></label>
    </p>

    <p>
    <label for="disc_state">State: <input id="disc_state" name="disc_state" type="text" /></label>
    </p>

    <p>
    <label for="disc_zip">Zip: <input id="disc_zip" name="disc_zip" type="text" /></label>
    </p>

    <p>
    <label for="disc_sig">Signature: <input id="disc_sig" name="disc_sig" type="text" /></label>
    </p>

    <p>
    <label for="disc_date">Date: <input id="disc_date" name="disc_date" type="text" /></label>
    </p>

    <p>
    <label for="disc_employer">Prospective Employer: <input id="disc_employer" name="disc_employer" type="text" /></label>
    </p>

    <em>Para información en español, visite <a href="www.consumerfinance.gov/learnmore" target="_blank">www.consumerfinance.gov/learnmore</a> o escribe al Consumer Financial Protection Bureau, 1700 G Street N.W., Washington, DC 20552.</em>

  </td>
</tr>

<tr>
  <td colspan="12">
    <span class="heading">A Summary of Your Rights Under the Fair Credit Reporting Act</span>
  </td>
</tr>

<tr>
  <td colspan="12">
    <p>
    The federal Fair Credit Reporting Act (FCRA) promotes the accuracy, fairness, and privacy of information in the files of consumer reporting agencies. There are many types of consumer reporting agencies, including credit bureaus and specialty agencies (such as agencies that sell information about check writing histories, medical records, and rental history records). Here is a summary of your major rights under the FCRA. <strong>For more information, including information about additional rights, go to www.consumerfinance.gov/learnmore or write to: Consumer Financial Protection Bureau, 1700 G Street N.W., Washington, DC 20552.</strong>
    </p>

    <ul>

      <li style="margin-bottom: 10px;">
        <strong>You must be told if information in your file has been used against you.</strong> Anyone who uses a credit report or another type of consumer report to deny your application for credit, insurance, or employment – or to take another adverse action against you – must tell you, and must give you the name, address, and phone number of the agency that provided the information. 
      </li>

      <li style="margin-bottom: 10px;">
        <strong>You have the right to know what is in your file.</strong> You may request and obtain all the information about you in the files of a consumer reporting agency (your "file disclosure"). You will be required to provide proper identification, which may include your Social Security number. In many cases, the disclosure will be free. You are entitled to a free file disclosure if:
        <ul>
          <li>a person has taken adverse action against you because of information in your credit report;</li>
          <li>you are the victim of identity theft and place a fraud alert in your file;</li>
          <li>your file contains inaccurate information as a result of fraud;</li>
          <li>you are on public assistance;</li>
          <li>you are unemployed but expect to apply for employment within 60 days.</li>
        </ul>
        <br/>
        In addition, all consumers are entitled to one free disclosure every 12 months upon request from each nationwide credit bureau and from nationwide specialty consumer reporting agencies. See www.consumerfinance.gov/learnmore for additional information. 
      </li>

      <li style="margin-bottom: 10px;">
        <strong>You have the right to ask for a credit score.</strong> Credit scores are numerical summaries of your credit-worthiness based on information from credit bureaus. You may request a credit score from consumer reporting agencies that create scores or distribute scores used in residential real property loans, but you will have to pay for it. In some mortgage transactions, you will receive credit score information for free from the mortgage lender. 
      </li>

      <li style="margin-bottom: 10px;">
        <strong>You have the right to dispute incomplete or inaccurate information.</strong> If you identify information in your file that is incomplete or inaccurate, and report it to the consumer reporting agency, the agency must investigate unless your dispute is frivolous. See www.consumerfinance.gov/learnmore for an explanation of dispute procedures. 
      </li>

      <li style="margin-bottom: 10px;">
        <strong>Consumer reporting agencies must correct or delete inaccurate, incomplete, or unverifiable information.</strong> Inaccurate, incomplete or unverifiable information must be removed or corrected, usually within 30 days. However, a consumer reporting agency may continue to report information it has verified as accurate. 
      </li>

      <li style="margin-bottom: 10px;">
        <strong>Consumer reporting agencies may not report outdated negative information.</strong> In most cases, a consumer reporting agency may not report negative information that is more than seven years old, or bankruptcies that are more than 10 years old.
      </li>

      <li style="margin-bottom: 10px;">
        <strong>Access to your file is limited.</strong> A consumer reporting agency may provide information about you only to people with a valid need -- usually to consider an application with a creditor, insurer, employer, landlord, or other business. The FCRA specifies those with a valid need for access.
      </li>

      <li style="margin-bottom: 10px;">
        <strong>You must give your consent for reports to be provided to employers.</strong> A consumer reporting agency may not give out information about you to your employer, or a potential employer, without your written consent given to the employer. Written consent generally is not required in the trucking industry. For more information, go to www.consumerfinance.gov/learnmore. 
      </li>

      <li style="margin-bottom: 10px;">
        <strong>You may limit "prescreened" offers of credit and insurance you get based on information in your credit report.</strong> Unsolicited "prescreened" offers for credit and insurance must include a toll-free phone number you can call if you choose to remove your name and address from the lists these offers are based on. You may opt out with the nationwide credit bureaus at 1-888-5-OPTOUT (1-888-567-8688). 
      </li>

      <li style="margin-bottom: 10px;">
        <strong>You may seek damages from violators.</strong> If a consumer reporting agency, or, in some cases, a user of consumer reports or a furnisher of information to a consumer reporting agency violates the FCRA, you may be able to sue in state or federal court. 
      </li>

      <li>
        <strong>Identity theft victims and active duty military personnel have additional rights.</strong> For more information, visit <a href="www.consumerfinance.gov/learnmore" target="_blank">www.consumerfinance.gov/learnmore</a>.
      </li>

    </ul>
  </td>
</tr>

<tr>
  <td colspan="12">
    <span class="heading">ICRA</span>
  </td>
</tr>

<tr>
  <td colspan="12">
    <h3>A Summary of Your Rights Under the Provisions of California Civil Code Section 1786.22</h3>
    <p>
    The Investigative Consumer Reporting Agencies Act (ICRA) is designed to promote accuracy, fairness, and privacy of information in the files of every 
    "consumer reporting agency" (CRA). You can find the complete text of the ICRA, at the California Privacy Protection web site 
    <a href="http://www.privacy.ca.gov/icraa.htm" target="_blank">(http://www.privacy.ca.gov/icraa.htm)</a>. The ICRA gives you specific rights, as 
    outlined below. You may have additional rights under federal law. You may contact a state or local consumer protection agency or a state attorney 
    general to learn those rights. 
    </p>

    <p>
    (a) An investigative consumer reporting agency shall supply files and information required under Section 1786.10 during normal business hours 
    and on reasonable notice.<br/><br/> 
    (b) Files maintained on a consumer shall be made available for the consumer's visual inspection, as follows:<br/> 
      <span style="margin-left: 10px; display: block;">
      (1) In person, if he appears in person and furnishes proper identification. A copy of his file shall also be available to the consumer for a 
      fee not to exceed the actual costs of duplication services provided. (2) By certified mail, if he makes a written request, with proper 
      identification, for copies to be sent to a specified addressee. Investigative consumer reporting agencies complying with requests for 
      certified mailings under this section shall not be liable for disclosures to third parties caused by mishandling of mail after such mailings 
      leave the investigative consumer reporting agencies. (3) A summary of all information contained in files on a consumer and required to be 
      provided by Section 1786.10 shall be provided by telephone, if the consumer has made a written request, with proper identification for 
      telephone disclosure, and the toll charge, if any, for the telephone call is prepaid by or charged directly to the consumer. 
      </span><br/>
    (c) The term "proper identification" as used in subdivision (b) shall mean that information generally deemed sufficient to identify a person. 
    Such information includes documents such as a valid driver’s license, social security account number, military identification card, and credit 
    cards. Only if the consumer is unable to reasonably identify himself with the information described above, may an investigative consumer reporting 
    agency require additional information concerning the consumer's employment and personal or family history in order to verify his identity.<br/> 
    (d) The investigative consumer reporting agency shall provide trained personnel to explain to the consumer any information furnished him pursuant 
    to Section 1786.10.<br/><br/>
    (e) The investigative consumer reporting agency shall provide a written explanation of any coded information contained in 
    files maintained on a consumer. This written explanation shall be distributed whenever a file is provided to a consumer for visual inspection 
    as required under Section 1786.22.<br/><br/>
    (f) The consumer shall be permitted to be accompanied by one other person of his choosing, who shall furnish 
    reasonable identification. An investigative consumer reporting agency may require the consumer to furnish a written statement granting permission 
    to the consumer reporting agency to discuss the consumer's file in such person's presence.
    </p>
  </td>
</tr>

<tr>
  <td colspan="12">
    <span class="heading">New York Correction Law</span>
  </td>
</tr>

<tr>
  <td colspan="12">
    <h3>
    ARTICLE 23-A<br/>
    LICENSURE AND EMPLOYMENT OF PERSONS PREVIOUSLY CONVICTED OF ONE OR MORE CRIMINAL OFFENSES
    </h3>

    <p>
    <strong>Section 750. Definitions.</strong>
    </p>

    <p>
    <strong>Section 751. Applicability.</strong>
    </p>

    <p>
    <strong>Section 752. Unfair discrimination against persons previously convicted of one or more criminal offenses prohibited.</strong>
    </p>

    <p>
    <strong>Section 753. Factors to be considered concerning a previous criminal conviction; presumption.</strong>
    </p>

    <p>
    <strong>Section 754. Written statement upon denial of license or employment.</strong>
    </p>

    <p>
    <strong>Section 755. Enforcement.</strong>
    </p>

    <p>
    <strong>§750. Definitions.</strong><br/>
    For the purposes of this article, the following terms shall have the following meanings:<br/>
    (1) "Public agency" means the state or any local subdivision thereof, or any state or local department, agency, board or
    commission.<br/>
    (2) "Private employer" means any person, company, corporation, labor organization or association which employs ten or more persons.<br/>
    (3) "Direct relationship" means that the nature of criminal conduct for which the person was convicted has a direct bearing on his fitness or 
    ability to perform one or more of the duties or responsibilities necessarily related to the license, opportunity, or job in question.<br/>
    (4) "License" means any certificate, license, permit or grant of permission required by the laws of this state, its political
    subdivisions or instrumentalities as a condition for the lawful practice of any occupation, employment, trade, vocation,
    business, or profession. Provided, however, that "license" shall not, for the purposes of this article, include any license or
    permit to own, possess, carry, or fire any explosive, pistol, handgun, rifle, shotgun, or other firearm.<br/>
    (5) "Employment" means any occupation, vocation or employment, or any form of vocational or educational training. Provided, however, that 
    "employment" shall not, for the purposes of this article, include membership in any law enforcement agency.
    </p>

    <p>
    <strong>§751. Applicability.</strong><br/>
    The provisions of this article shall apply to any application by any person for a license or employment at any public or private employer, 
    who has previously been convicted of one or more criminal offenses in this state or in any other jurisdiction, and to any license or 
    employment held by any person whose conviction of one or more criminal offenses in this state or in any other jurisdiction preceded 
    such employment or granting of a license, except where a mandatory forfeiture, disability or bar to employment is imposed by law, 
    and has not been removed by an executive pardon, certificate of relief from disabilities or certificate of good conduct. Nothing 
    in this article shall be construed to affect any right an employer may have with respect to an intentional misrepresentation in 
    connection with an application for employment made by a prospective employee or previously made by a current employee.
    </p>

    <p>
    <strong>§752. Unfair discrimination against persons previously convicted of one or more criminal offenses prohibited.</strong><br/>
    No application for any license or employment, and no employment or license held by an individual, to which the provisions of this article are applicable, shall be denied or acted upon adversely by reason of the individual's having been previously
    convicted of one or more criminal offenses, or by reason of a finding of lack of "good moral character" when such finding is
    based upon the fact that the individual has previously been convicted of one or more criminal offenses, unless:<br/>
    (1) There is a direct relationship between one or more of the previous criminal offenses and the specific license or
    employment sought or held by the individual; or<br/>
    (2) the issuance or continuation of the license or the granting or continuation of the employment would involve an
    unreasonable risk to property or to the safety or welfare of specific individuals or the general public.
    </p>

    <p>
    <strong>§753. Factors to be considered concerning a previous criminal conviction; presumption.</strong><br/>
    1. In making a determination pursuant to section seven hundred fifty-two of this chapter, the public agency or
    private employer shall consider the following factors:<br/>
    (a) The public policy of this state, as expressed in this act, to encourage the licensure and employment of persons
    previously convicted of one or more criminal offenses.<br/>
    (b) The specific duties and responsibilities necessarily related to the license or employment sought or held by the
    person.<br/>
    (c) The bearing, if any, the criminal offense or offenses for which the person was previously convicted will have on his
    fitness or ability to perform one or more such duties or responsibilities.<br/>
    (d) The time which has elapsed since the occurrence of the criminal offense or offenses.<br/>
    (e) The age of the person at the time of occurrence of the criminal offense or offenses.<br/>
    (f) The seriousness of the offense or offenses.<br/>
    (g) Any information produced by the person, or produced on his behalf, in regard to his rehabilitation and good
    conduct.<br/>
    (h) The legitimate interest of the public agency or private employer in protecting property, and the safety and welfare
    of specific individuals or the general public.<br/>
    2. In making a determination pursuant to section seven hundred fifty-two of this chapter, the public agency or private employer 
    shall also give consideration to a certificate of relief from disabilities or a certificate of good conduct issued to the applicant, 
    which certificate shall create a presumption of rehabilitation in regard to the offense or offenses specified therein.
    </p>

    <p>
    <strong>§754. Written statement upon denial of license or employment.</strong><br/>
    At the request of any person previously convicted of one or more criminal offenses who has been denied a license or
    employment, a public agency or private employer shall provide, within thirty days of a request, a written statement 
    setting forth the reasons for such denial.
    </p>

    <p>
    <strong>§755. Enforcement.</strong><br/>
    1. In relation to actions by public agencies, the provisions of this article shall be enforceable by a proceeding brought pursuant 
    to article seventy-eight of the civil practice law and rules.<br/>
    2. In relation to actions by private employers, the provisions of this article shall be enforceable by the division of human rights 
    pursuant to the powers and procedures set forth in article fifteen of the executive law, and, concurrently, by the New York city commission on human rights.
    </p>
  </td>
</tr>

</table>

<p>
Note: You will be given an opportunity to upload attachments after you submit this part of your application.
</p>



<div>
<input type="hidden" name="page" value="edit">
<input type="hidden" name="action" value="submit">
<input type="hidden" name="uid" value="<?php echo (isset($user["uid"]) ? $user["uid"] : ""); ?>">
<input type="hidden" name="pw" value="<?php echo (isset($user["pw"]) ? $user["pw"] : ""); ?>">
<input type="hidden" name="attach" value="1">
<input type="hidden" name="token" value="<?php echo (isset($token) ? $token : ""); ?>">
<button type="submit" id="submit">Submit Application for Review</button>
</div>

</form>
<script type="text/javascript">
   var jobcount = <?php echo $jobcount ?>;
</script>

<?php include("pagewrap.inc.php"); ?>
